'use strict';
const DB_NAME='manual', STORE='manuals';
let db, manuals=[], currentId=null, saveTimer, toastTimer, deleteArmed=false;
const $=id=>document.getElementById(id);
const ui={home:$('homeView'),detail:$('detailView'),list:$('manualList'),empty:$('emptyState'),noResults:$('noResults'),count:$('resultCount'),search:$('searchInput'),photo:$('photoInput'),busy:$('busyOverlay'),title:$('titleInput'),text:$('textInput'),detailPhoto:$('detailPhoto'),saveStatus:$('saveStatus'),sheet:$('deleteSheet'),deleteConfirm:$('deleteConfirm'),toast:$('toast')};

function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE,{keyPath:'id'})};req.onsuccess=()=>{db=req.result;resolve(db)};req.onerror=()=>reject(req.error)})}
function request(storeMode,action){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,storeMode),store=tx.objectStore(STORE),req=action(store);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
const getAll=()=>request('readonly',s=>s.getAll()); const put=item=>request('readwrite',s=>s.put(item)); const remove=id=>request('readwrite',s=>s.delete(id));
function escapeHTML(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function displayDate(value){return new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric'}).format(new Date(value))}
function render(){const q=ui.search.value.trim().toLocaleLowerCase('ko');const shown=manuals.filter(m=>(`${m.title} ${m.text}`).toLocaleLowerCase('ko').includes(q)).sort((a,b)=>b.createdAt-a.createdAt);ui.list.innerHTML=shown.map(m=>`<button class="manual-card" type="button" data-id="${m.id}"><span class="thumb-wrap"><img class="thumb" src="${m.photo}" alt=""><span class="scan-badge" ${m.title==='스캔 중...'?'':'hidden'}>글자 인식 중...</span></span><span class="card-copy"><h2>${escapeHTML(m.title)}</h2><span class="preview">${escapeHTML(m.text||'인식된 글이 아직 없어요.')}</span><span class="date">${displayDate(m.createdAt)}</span></span></button>`).join('');ui.empty.hidden=manuals.length!==0;ui.noResults.hidden=!(manuals.length>0&&shown.length===0);ui.count.textContent=manuals.length?`${shown.length}개의 설명서`:''}
function showToast(message){clearTimeout(toastTimer);ui.toast.textContent=message;ui.toast.hidden=false;toastTimer=setTimeout(()=>ui.toast.hidden=true,3200)}
function uuid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`}
function resizeImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('image'));img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.82))};img.src=reader.result};reader.readAsDataURL(file)})}
function autoTitle(text){const noise=/^(?:\d+|[-–—_.·•]+|(?:page|p\.?|쪽)\s*\d*)$/i;const lines=text.split(/\r?\n/).map(s=>s.replace(/\s+/g,' ').trim()).filter(Boolean);for(const line of lines){const chars=line.replace(/\s/g,'');if(line.length<=40&&chars.length>=3&&!noise.test(line)&&/[A-Za-z가-힣]/.test(line))return line}return '제목 없는 설명서'}
async function processPhoto(file){ui.busy.hidden=false;let photo;try{photo=await resizeImage(file)}catch(e){ui.busy.hidden=true;showToast('사진을 불러오지 못했어요. 다시 시도해 주세요.');return}const now=Date.now(),item={id:uuid(),title:'스캔 중...',text:'',photo,createdAt:now,updatedAt:now};await put(item);manuals.push(item);ui.busy.hidden=true;render();showToast('사진을 저장했어요. 이제 글자를 읽을게요.');runOCR(item.id,photo)}
async function runOCR(id,photo){try{if(!window.Tesseract)throw new Error('OCR library unavailable');const worker=await Tesseract.createWorker(['kor','eng'],1,{workerPath:'./ocr/worker.min.js',corePath:'./ocr/tesseract-core-lstm.wasm.js',langPath:'./ocr/lang',cacheMethod:'none'});let text='';try{({data:{text}}=await worker.recognize(photo))}finally{await worker.terminate()}const item=manuals.find(m=>m.id===id);if(!item)return;item.title=autoTitle(text);item.text=text.trim();item.updatedAt=Date.now();await put(item);render();if(currentId===id){ui.title.value=item.title;ui.text.value=item.text;ui.saveStatus.textContent=''}showToast('글자 인식을 마쳤어요.')}catch(error){const item=manuals.find(m=>m.id===id);if(item){item.title='제목 없는 설명서';item.text='';item.updatedAt=Date.now();await put(item);render();if(currentId===id){ui.title.value=item.title;ui.text.value='';ui.saveStatus.textContent=''}}showToast('글자를 읽지 못했지만 사진은 안전하게 저장했어요.')}}
function openDetail(id){const item=manuals.find(m=>m.id===id);if(!item)return;currentId=id;ui.detailPhoto.src=item.photo;ui.title.value=item.title;ui.text.value=item.text;ui.saveStatus.textContent=item.title==='스캔 중...'?'글자 인식 중...':'';ui.home.hidden=true;ui.detail.hidden=false;scrollTo(0,0);history.pushState({detail:id},'',`#${id}`)}
function closeDetail(updateHistory=true){currentId=null;ui.detail.hidden=true;ui.home.hidden=false;render();if(updateHistory&&location.hash)history.back();else history.replaceState({},'',location.pathname+location.search)}
function scheduleSave(){ui.saveStatus.textContent='저장 중...';clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{const item=manuals.find(m=>m.id===currentId);if(!item)return;item.title=ui.title.value.trim()||'제목 없는 설명서';item.text=ui.text.value;item.updatedAt=Date.now();await put(item);ui.saveStatus.textContent='저장됨';setTimeout(()=>{if(ui.saveStatus.textContent==='저장됨')ui.saveStatus.textContent=''},1500)},450)}
async function dailyBackup(){const key='manual-last-backup',today=new Date().toISOString().slice(0,10);if(localStorage.getItem(key)===today)return;try{const payload=manuals.map(({id,title,text,createdAt})=>({id,title,text,createdAt}));const response=await fetch('https://appointee-unnoticed-donated.ngrok-free.dev/api/app-backup/manual',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(response.ok)localStorage.setItem(key,today)}catch(e){}}
function showDeleteSheet(){deleteArmed=false;ui.deleteConfirm.classList.remove('armed');ui.deleteConfirm.textContent='한 번 더 눌러 삭제';ui.sheet.hidden=false}
async function confirmDelete(){if(!deleteArmed){deleteArmed=true;ui.deleteConfirm.classList.add('armed');ui.deleteConfirm.textContent='정말 삭제하기';return}const id=currentId;await remove(id);manuals=manuals.filter(m=>m.id!==id);ui.sheet.hidden=true;closeDetail();showToast('설명서를 삭제했어요.')}
async function init(){try{await openDB();manuals=await getAll();render();dailyBackup()}catch(e){showToast('저장 공간을 열지 못했어요. 앱을 다시 실행해 주세요.')}if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(reg=>reg.update()).catch(()=>{});let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading)return;reloading=true;location.reload()})}}
$('addButton').addEventListener('click',()=>ui.photo.click());$('emptyAddButton').addEventListener('click',()=>ui.photo.click());ui.photo.addEventListener('change',()=>{const file=ui.photo.files[0];if(file)processPhoto(file);ui.photo.value=''});ui.search.addEventListener('input',render);ui.list.addEventListener('click',e=>{const card=e.target.closest('[data-id]');if(card)openDetail(card.dataset.id)});$('backButton').addEventListener('click',()=>closeDetail());ui.title.addEventListener('input',scheduleSave);ui.text.addEventListener('input',scheduleSave);$('deleteButton').addEventListener('click',showDeleteSheet);$('deleteCancel').addEventListener('click',()=>ui.sheet.hidden=true);ui.sheet.addEventListener('click',e=>{if(e.target===ui.sheet)ui.sheet.hidden=true});ui.deleteConfirm.addEventListener('click',confirmDelete);addEventListener('popstate',()=>{if(!ui.detail.hidden)closeDetail(false)});init();
